start Win32\Debug\Evemini --window-name="Calculator1" --form-left=400 --form-width=90 --always-visible=true
start Win32\Debug\Evemini --window-name="Calculator1" --form-left=400 --form-width=90 --always-visible=true
start Win32\Debug\Evemini --window-name="Calculator1" --form-left=400 --form-width=90 --always-visible=true
start Win32\Debug\Evemini --window-name="Calculator1" --form-left=400 --form-width=90 --always-visible=true
start Win32\Debug\Evemini --window-name="Calculator1" --form-left=400 --form-width=90 --always-visible=true
start Win32\Debug\Evemini --window-name="Calculator1" --form-left=400 --form-width=90 --always-visible=true
start Win32\Debug\Evemini --window-name="Calculator1" --form-left=400 --form-width=90 --always-visible=true
start Win32\Debug\Evemini --window-name="Calculator1" --form-left=400 --form-width=90 --always-visible=true
start Win32\Debug\Evemini --window-name="Calculator1" --form-left=400 --form-width=90 --always-visible=true
start Win32\Debug\Evemini --window-name="Calculator1" --form-left=400 --form-width=90 --always-visible=true
start Win32\Debug\Evemini --window-name="Calculator1" --form-left=400 --form-width=90 --always-visible=true
start Win32\Debug\Evemini --window-name="Calculator1" --form-left=400 --form-width=90 --always-visible=true
start Win32\Debug\Evemini --window-name="Calculator1" --form-left=400 --form-width=90 --always-visible=true
start Win32\Debug\Evemini --window-name="Calculator1" --form-left=400 --form-width=90 --always-visible=true
start Win32\Debug\Evemini --window-name="Calculator1" --form-left=400 --form-width=90 --always-visible=true
start Win32\Debug\Evemini --window-name="Calculator1" --form-left=400 --form-width=90 --always-visible=true
start Win32\Debug\Evemini --window-name="Calculator1" --form-left=400 --form-width=90 --always-visible=true
start Win32\Debug\Evemini --window-name="Calculator1" --form-left=400 --form-width=90 --always-visible=true
start Win32\Debug\Evemini --window-name="Calculator1" --form-left=400 --form-width=90 --always-visible=true
start Win32\Debug\Evemini --window-name="Calculator1" --form-left=400 --form-width=90 --always-visible=true
start Win32\Debug\Evemini --window-name="Calculator1" --form-left=400 --form-width=90 --always-visible=true
start Win32\Debug\Evemini --window-name="Calculator1" --form-left=400 --form-width=90 --always-visible=true
start Win32\Debug\Evemini --window-name="Calculator1" --form-left=400 --form-width=90 --always-visible=true
start Win32\Debug\Evemini --window-name="Calculator1" --form-left=400 --form-width=90 --always-visible=true
start Win32\Debug\Evemini --window-name="Calculator1" --form-left=400 --form-width=90 --always-visible=true
start Win32\Debug\Evemini --window-name="Calculator1" --form-left=400 --form-width=90 --always-visible=true
start Win32\Debug\Evemini --window-name="Calculator1" --form-left=400 --form-width=90 --always-visible=true
start Win32\Debug\Evemini --window-name="Calculator1" --form-left=400 --form-width=90 --always-visible=true
start Win32\Debug\Evemini --window-name="Calculator1" --form-left=400 --form-width=90 --always-visible=true
start Win32\Debug\Evemini --window-name="Calculator1" --form-left=400 --form-width=90 --always-visible=true
start Win32\Debug\Evemini --window-name="Calculator1" --form-left=400 --form-width=90 --always-visible=true
start Win32\Debug\Evemini --window-name="Calculator1" --form-left=400 --form-width=90 --always-visible=true
start Win32\Debug\Evemini --window-name="Calculator1" --form-left=400 --form-width=90 --always-visible=true
start Win32\Debug\Evemini --window-name="Calculator1" --form-left=400 --form-width=90 --always-visible=true
start Win32\Debug\Evemini --window-name="Calculator1" --form-left=400 --form-width=90 --always-visible=true
start Win32\Debug\Evemini --window-name="Calculator1" --form-left=400 --form-width=90 --always-visible=true
start Win32\Debug\Evemini --window-name="Calculator1" --form-left=400 --form-width=90 --always-visible=true
start Win32\Debug\Evemini --window-name="Calculator1" --form-left=400 --form-width=90 --always-visible=true
start Win32\Debug\Evemini --window-name="Calculator1" --form-left=400 --form-width=90 --always-visible=true
start Win32\Debug\Evemini --window-name="Calculator1" --form-left=400 --form-width=90 --always-visible=true
start Win32\Debug\Evemini --window-name="Calculator1" --form-left=400 --form-width=90 --always-visible=true
start Win32\Debug\Evemini --window-name="Calculator1" --form-left=400 --form-width=90 --always-visible=true
start Win32\Debug\Evemini --window-name="Calculator1" --form-left=400 --form-width=90 --always-visible=true
start Win32\Debug\Evemini --window-name="Calculator1" --form-left=400 --form-width=90 --always-visible=true
start Win32\Debug\Evemini --window-name="Calculator1" --form-left=400 --form-width=90 --always-visible=true
start Win32\Debug\Evemini --window-name="Calculator1" --form-left=400 --form-width=90 --always-visible=true
start Win32\Debug\Evemini --window-name="Calculator1" --form-left=400 --form-width=90 --always-visible=true
start Win32\Debug\Evemini --window-name="Calculator1" --form-left=400 --form-width=90 --always-visible=true
start Win32\Debug\Evemini --window-name="Calculator1" --form-left=400 --form-width=90 --always-visible=true
start Win32\Debug\Evemini --window-name="Calculator1" --form-left=400 --form-width=90 --always-visible=true
start Win32\Debug\Evemini --window-name="Calculator1" --form-left=400 --form-width=90 --always-visible=true
start Win32\Debug\Evemini --window-name="Calculator1" --form-left=400 --form-width=90 --always-visible=true
start Win32\Debug\Evemini --window-name="Calculator1" --form-left=400 --form-width=90 --always-visible=true
start Win32\Debug\Evemini --window-name="Calculator1" --form-left=400 --form-width=90 --always-visible=true
start Win32\Debug\Evemini --window-name="Calculator1" --form-left=400 --form-width=90 --always-visible=true
start Win32\Debug\Evemini --window-name="Calculator1" --form-left=400 --form-width=90 --always-visible=true
start Win32\Debug\Evemini --window-name="Calculator1" --form-left=400 --form-width=90 --always-visible=true
start Win32\Debug\Evemini --window-name="Calculator1" --form-left=400 --form-width=90 --always-visible=true
start Win32\Debug\Evemini --window-name="Calculator1" --form-left=400 --form-width=90 --always-visible=true
start Win32\Debug\Evemini --window-name="Calculator1" --form-left=400 --form-width=90 --always-visible=true
start Win32\Debug\Evemini --window-name="Calculator1" --form-left=400 --form-width=90 --always-visible=true
start Win32\Debug\Evemini --window-name="Calculator1" --form-left=400 --form-width=90 --always-visible=true
start Win32\Debug\Evemini --window-name="Calculator1" --form-left=400 --form-width=90 --always-visible=true
start Win32\Debug\Evemini --window-name="Calculator1" --form-left=400 --form-width=90 --always-visible=true
start Win32\Debug\Evemini --window-name="Calculator1" --form-left=400 --form-width=90 --always-visible=true
start Win32\Debug\Evemini --window-name="Calculator1" --form-left=400 --form-width=90 --always-visible=true
start Win32\Debug\Evemini --window-name="Calculator1" --form-left=400 --form-width=90 --always-visible=true
start Win32\Debug\Evemini --window-name="Calculator1" --form-left=400 --form-width=90 --always-visible=true
start Win32\Debug\Evemini --window-name="Calculator1" --form-left=400 --form-width=90 --always-visible=true
start Win32\Debug\Evemini --window-name="Calculator1" --form-left=400 --form-width=90 --always-visible=true
start Win32\Debug\Evemini --window-name="Calculator1" --form-left=400 --form-width=90 --always-visible=true
start Win32\Debug\Evemini --window-name="Calculator1" --form-left=400 --form-width=90 --always-visible=true
start Win32\Debug\Evemini --window-name="Calculator1" --form-left=400 --form-width=90 --always-visible=true
start Win32\Debug\Evemini --window-name="Calculator1" --form-left=400 --form-width=90 --always-visible=true
start Win32\Debug\Evemini --window-name="Calculator1" --form-left=400 --form-width=90 --always-visible=true
start Win32\Debug\Evemini --window-name="Calculator1" --form-left=400 --form-width=90 --always-visible=true
start Win32\Debug\Evemini --window-name="Calculator1" --form-left=400 --form-width=90 --always-visible=true
start Win32\Debug\Evemini --window-name="Calculator1" --form-left=400 --form-width=90 --always-visible=true
start Win32\Debug\Evemini --window-name="Calculator1" --form-left=400 --form-width=90 --always-visible=true
start Win32\Debug\Evemini --window-name="Calculator1" --form-left=400 --form-width=90 --always-visible=true
start Win32\Debug\Evemini --window-name="Calculator1" --form-left=400 --form-width=90 --always-visible=true
start Win32\Debug\Evemini --window-name="Calculator1" --form-left=400 --form-width=90 --always-visible=true
start Win32\Debug\Evemini --window-name="Calculator1" --form-left=400 --form-width=90 --always-visible=true
start Win32\Debug\Evemini --window-name="Calculator1" --form-left=400 --form-width=90 --always-visible=true
start Win32\Debug\Evemini --window-name="Calculator1" --form-left=400 --form-width=90 --always-visible=true
start Win32\Debug\Evemini --window-name="Calculator1" --form-left=400 --form-width=90 --always-visible=true
start Win32\Debug\Evemini --window-name="Calculator1" --form-left=400 --form-width=90 --always-visible=true
start Win32\Debug\Evemini --window-name="Calculator1" --form-left=400 --form-width=90 --always-visible=true
start Win32\Debug\Evemini --window-name="Calculator1" --form-left=400 --form-width=90 --always-visible=true
start Win32\Debug\Evemini --window-name="Calculator1" --form-left=400 --form-width=90 --always-visible=true
start Win32\Debug\Evemini --window-name="Calculator1" --form-left=400 --form-width=90 --always-visible=true
start Win32\Debug\Evemini --window-name="Calculator1" --form-left=400 --form-width=90 --always-visible=true
start Win32\Debug\Evemini --window-name="Calculator1" --form-left=400 --form-width=90 --always-visible=true
start Win32\Debug\Evemini --window-name="Calculator1" --form-left=400 --form-width=90 --always-visible=true
start Win32\Debug\Evemini --window-name="Calculator1" --form-left=400 --form-width=90 --always-visible=true
start Win32\Debug\Evemini --window-name="Calculator1" --form-left=400 --form-width=90 --always-visible=true
start Win32\Debug\Evemini --window-name="Calculator1" --form-left=400 --form-width=90 --always-visible=true
start Win32\Debug\Evemini --window-name="Calculator1" --form-left=400 --form-width=90 --always-visible=true
start Win32\Debug\Evemini --window-name="Calculator1" --form-left=400 --form-width=90 --always-visible=true
start Win32\Debug\Evemini --window-name="Calculator1" --form-left=400 --form-width=90 --always-visible=true
pause
