object FormOverlay: TFormOverlay
  Left = 0
  Top = 0
  BorderStyle = bsNone
  Caption = 'FormOverlay'
  ClientHeight = 450
  ClientWidth = 868
  Color = clBtnFace
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'Tahoma'
  Font.Style = []
  FormStyle = fsStayOnTop
  GlassFrame.Enabled = True
  GlassFrame.SheetOfGlass = True
  OldCreateOrder = False
  OnActivate = FormActivateOrShow
  OnCreate = FormCreate
  PixelsPerInch = 96
  TextHeight = 13
end
